export const ADD_QUESTION = "ADD_QUESTION";
export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const ADD_QUESTION_FAIL = "ADD_QUESTION_FAIL";

export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const UPDATE_QUESTION_FAIL = "UPDATE_QUESTION_FAIL";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";

export const SEARCH_QUESTION = "SEARCH_QUESTION";
export const SEARCH_QUESTION_FAIL = "SEARCH_QUESTION_FAIL";
export const SEARCH_QUESTION_SUCCESS = "SEARCH_QUESTION_SUCCESS";

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";
export const GET_TOTAL_COUNT_FAIL = "GET_TOTAL_COUNT_FAIL";
export const GET_TOTAL_COUNT_SUCCESS = "GET_TOTAL_COUNT_SUCCESS";

export const GET_LEETCODE_COUNT = "GET_LEETCODE_COUNT";
export const GET_LEETCODE_COUNT_FAIL = "GET_LEETCODE_COUNT_FAIL";
export const GET_LEETCODE_COUNT_SUCCESS = "GET_LEETCODE_COUNT_SUCCESS";